### ISSUE TITLE
Fail in testing with vpp docker image and cni

### ISSUE THREAD

**Issue by ylhsiehitri** [intel/userspace-cni-network-plugin#35]
Hello,

I followed the instructions in https://github.com/intel/userspace-cni-network-plugin/blob/master/README.md#testing-with-vpp-docker-image-and-cni,
but failed in `exec-plugins.sh` when it tried to execute `/opt/cni/bin/userspace < /etc/cni/net.d/90-userspace.conf`. The output error is as below.
(the `exec-plugins.sh` is called in the `usrsp-docker-run.sh` that called in the instructions above)

```
2019-12-03T10:00:05Z [error] GetPod: No kubeClient: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe9a9d7]

goroutine 1 [running, locked to thread]:
github.com/intel/userspace-cni-network-plugin/pkg/annotations.GetPodVolumeMountHostSharedDir(0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/pkg/annotations/annotations.go:66 +0x47
main.getPodAndSharedDir(0xc00033a500, 0xc00030bc70, 0x0, 0x0, 0x4, 0x0, 0xf3b8a0, 0xc000353b10, 0x16, 0x0, ...)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/userspace/userspace.go:125 +0x7b1
main.cmdDel(0xc00030bc70, 0x0, 0x0, 0x0, 0x0, 0x5, 0x0)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/userspace/userspace.go:332 +0x333
main.main.func3(0xc00030bc70, 0xc000047650, 0x5)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/userspace/userspace.go:438 +0x38
github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc000133e90, 0xc00030bc70, 0x1223880, 0xc000354c60, 0x116d440, 0x0, 0xc000133dd8)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:185 +0x185
github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc000133e90, 0x116d430, 0x116d438, 0x116d440, 0x1223880, 0xc000354c60, 0x1114a82, 0x2d, 0xbc443e07e59604e1)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:251 +0x33e
github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x116d430, 0x116d438, 0x116d440, 0x1223880, 0xc000354c60, 0x1114a82, 0x2d, 0xc000133f48)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:286 +0x110
github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x116d430, 0x116d438, 0x116d440, 0x1223880, 0xc000354c60, 0x1114a82, 0x2d)
        /root/go/src/github.com/intel/userspace-cni-network-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:301 +0x7a
main.main()
        /root/go/src/github.com/intel/userspace-cni-network-plugin/userspace/userspace.go:430 +0x72
```

ps. I have docker and K8s installed.

Thanks!

**Comment by dushyantbehl** [comment]
Facing the same issue with my cluster. Any progress on this?
